### ISSUE TITLE
execute_steps() does not works with behave-parallel

### ISSUE THREAD

**Issue by carlosmmelo** [vishalm/behave_parallel_demo#1]
Hey @vishalm I've just tested this,

However I'm using behave with selenium webdriver, and whenever I call the `execute_steps()` from a step definition file it fail with:

```
execute_steps() called outside of feature
```

And it works well when I dont use parallelization (without specifying the `process` and `parallel element`)

So it seems there is a bug with the `execute_steps()` (calling steps from a single step) can you try to confirm please?

this is how I've been using the `execute_steps()`:

```
@given('a "{role}" user')
def step_login_as(context, role):
    """
    Login as a "user_type" step
    """
    context.execute_steps(u'''
        Given the user is in the login page
        when the user logs in as "{0}"
        Then the user should be redirected to the dashboard page
    '''.format(role))
```

**Comment by khanhlhq** [comment]
Hey @carlosmmelo  and @vishalm,
Carlos run with command:
 'behave --processes 2 --parallel-element scenario --tags @testing'

When I debug I saw something:
This error comes from '/behave-parallel/behave/runner.py' : 

```
    def execute_steps(self, steps_text):       
        assert isinstance(steps_text, unicode), "Steps must be unicode."
        if not self.feature:
            raise ValueError('execute_steps() called outside of feature')
```

So that, I think when it called 'self.run_multiproc()' in '/behave-parallel/behave/runner.py' for multi_processes with scenario tags, it missed self.feature in run '/behave-parallel/behave/model.py' line 741.
I have tried to update this function like:

```
def run(self, runner):
        self._cached_status = None
        failed = False
        run_scenario = self.should_run(runner.config)
        run_steps = run_scenario and not runner.config.dry_run
        dry_run_scenario = run_scenario and runner.config.dry_run
        self.was_dry_run = dry_run_scenario

        if run_scenario or runner.config.show_skipped:
            for formatter in runner.formatters:
                formatter.scenario(self)

        runner.context._push()
        runner.context.scenario = self
        runner.context.tags = set(self.effective_tags)

        # update here:
        runner.context.feature = self.feature

        if not runner.config.dry_run and run_scenario:
            for tag in self.tags:
                runner.run_hook('before_tag', runner.context, tag)
            runner.run_hook('before_scenario', runner.context, self)
```

And it worked well.

Please have a look.

**Comment by vishalm** [comment]
@carlosmmelo you can do below patch

Use 
`step_matcher("re")`

Instead of 
`execute_steps()`

In your step definition file

**Comment by carlosmmelo** [comment]
@vishalm those are 2 different concepts, we want to be able to `execute_steps()` from a step regardless of the `step_matcher()`. Following the [Declarative style](http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html)

**Comment by vishalm** [comment]
Well behave-parallel is not my package and they haven't implemented 
`execute_steps()`
So for me `step_matcher("re")` worked !!
I am aware of this issue and I removed all `execute_steps()` from steps file and used  `step_matcher("re")` as it was desperate requirement for me.

And thought of telling everyone whoever facing this issue :)
